;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cosmetic.EyeColor.Black1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Blue1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Blue2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Blue3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Brown1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Brown2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Brown3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Brown4",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Green1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Green2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Green3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Green4",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Orange1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Orange2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Orange3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Pink2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Purple1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Purple2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Red1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Red2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Red3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Steel1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Steel2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Steel3",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Steel4",DevComment="")
+GameplayTagList=(Tag="Cosmetic.EyeColor.Yellow1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.1M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.2F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.2M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.3F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.3M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.4F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.4M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.5F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.5M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.6F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.6M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.7F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.7M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.8F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.8M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.AF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.AM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.BF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.BM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.CF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.CM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.D",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Black",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Blonde1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Blonde2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.BlueDark",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.BrownDark",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.BrownLight",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.BrownMid",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Ginger",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.GreenDark",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.GreenLight",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.GreenMid",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Orange",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Pink",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Purple",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Red",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.RootyTootyFruitySplash",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.SilverDark",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.SilverLight",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.SilverMid1",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.SilverMid2",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.White",DevComment="")
+GameplayTagList=(Tag="Cosmetic.HairColor.Yellow",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.1M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.2F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.2M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.3F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.3M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.4F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.4M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.5F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.5M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.6F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.6M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.7F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.7M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.8F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.8M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.AF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.AM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.BF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.BM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.CF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.CM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.D",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Item.Hammer.Swing",DevComment="")

