;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cosmetic.Eyes.1M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.2F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.2M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.3F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.3M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.4F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.4M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.5F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.5M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.6F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.6M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.7F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.7M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.8F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.8M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.AF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.AM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.BF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.BM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.CF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.CM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Eyes.D",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.1M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.2F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.2M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.3F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.3M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.4F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.4M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.5F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.5M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.6F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.6M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.7F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.7M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.8F",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.8M",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.AF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.AM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.BF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.BM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.CF",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.CM",DevComment="")
+GameplayTagList=(Tag="Cosmetic.Mouth.D",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Item.Hammer.Swing",DevComment="")

